baseURL = 'https://hugoblogapp.com'
languageCode = 'en-us'
title = 'Codebubble'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"